### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by hails** [shutsuga/moyashi#10]
# Posts
## Fields
- id
- name
- email
- password
- body
- timestamp
- parent
- bumped_at
- locked
## Concerns

How do we implement this?
ID as a `serial` and every post increments it?
How do we keep "one counter" per board? (i.e. every board have it's own `serial`)
Do we need to create a `BOARD_posts` for every board?

**Comment by czaks** [comment]
MySQL/MariaDB engines Aria and MyISAM support aggregate primary keys (eg.
board+id) and it works quite well.

InnoDB can't do that. It has transaction support though, so you can
implement a counter this way.

Dividing boards into separate tables may seem a tempting solution. It has
one plus: you can move some tables to other server. On the other hand, you
will need to do UNIONs to do things like overboard. UNIONs are expensive
and don't look like a clean code. This is what vichan-devel/vichan
currently does and it's an issue for a chan with many boards like 8chan.
